-- Generated by scripts/sol_map/build_sol_map.py from the game's Sol map files; regenerate,
-- don't edit. What exploring can't learn by walking: special exits {from, command, to}
-- (room numbers), rooms a ride holds you in on the way, rooms that kill on entry, and for
-- Akaturi pickup/dropoff rooms that need more than walking, the commands on the way there
-- (via) or what stands in the way (gate). Applied by mechanics.lua.
-- luacheck: no max line length
F2T_SOL_MECHANICS = {
    ["Brass"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Castillo"] = {
        special = {
            {136, "press button", 525},
            {525, "press button", 136},
        },
        transit = {},
        deadly = {},
        pickups = {
            ["Clive's Collectibles"] = {via = {"press button (Elevator)"}},
            ["Control room"] = {via = {"press button (Elevator)"}},
            ["Fedruckers"] = {via = {"press button (Elevator)"}},
            ["Office"] = {via = {"press button (Elevator)"}},
            ["Reception"] = {via = {"press button (Elevator)"}},
            ["Small office"] = {via = {"press button (Elevator)"}},
        },
    },
    ["Doris"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Earth"] = {
        special = {
            {515, "slide down banister", 580},
            {591, "press button", 783},
            {719, "press button", 527},
            {720, "press button", 783},
            {784, "press button", 721},
            {851, "open cell door", 852},
        },
        transit = {},
        deadly = {2195},
        pickups = {
            ["Communications and Services office"] = {via = {"press button (Elevator)"}},
            ["Computators office"] = {via = {"press button (Elevator)"}},
            ["Office of Administrative Affairs"] = {via = {"press button (Elevator)"}},
            ["Office of Armament Approval"] = {via = {"press button (Elevator)"}},
            ["Office of Financial and Fiduciary Approval"] = {via = {"press button (Elevator)"}},
            ["Office of Transport and Traffic Licensing"] = {via = {"press button (Elevator)"}},
            ["Office of World Management Approval"] = {via = {"press button (Elevator)"}},
            ["Office of the Minister for Administrative Affairs"] = {via = {"press button (Elevator)"}},
        },
    },
    ["Graveyard"] = {
        special = {
            {1436, "pull lever", 1435},
            {1672, "press stone", 1109},
            {1674, "lift latch", 1675},
            {1675, "lift latch", 1674},
            {1675, "push shelves", 1677},
            {1677, "pull shelves", 1675},
        },
        transit = {},
        deadly = {912, 914, 916, 1105},
        pickups = {
        },
    },
    ["Hunt"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Magellan"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Magrathea"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Mars"] = {
        special = {
            {389, "climb tree", 772},
        },
        transit = {},
        deadly = {79, 140, 524},
        pickups = {
        },
    },
    ["Mercury"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Paradise"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Pearl"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Phobos"] = {
        special = {
            {218, "press button 2", 920},
            {919, "press button 1", 217},
        },
        transit = {},
        deadly = {},
        pickups = {
            ["Flanario's room"] = {via = {"press button 2 (Buggy)"}, gate = "the buggy needs a keycard first: 'ask tracey for authorization' at the Help desk"},
            ["Home to Basil and his buddies"] = {via = {"press button 2 (Buggy)"}, gate = "the buggy needs a keycard first: 'ask tracey for authorization' at the Help desk"},
            ["Kitchen"] = {via = {"press button 2 (Buggy)"}, gate = "the buggy needs a keycard first: 'ask tracey for authorization' at the Help desk"},
        },
    },
    ["Rhea"] = {
        special = {
            {796, "climb back up", 789},
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Selena"] = {
        special = {
            {530, "press button", 601},
            {600, "press button", 529},
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Silk"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Starbase1"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Sumatra"] = {
        special = {
            {387, "get out", 515},
            {643, "press touchpad", 707},
            {707, "press touchpad", 643},
            {967, "press touchpad", 968},
            {968, "press touchpad", 967},
            {1026, "activate data unit", 1027},
            {1029, "press touchpad", 1030},
            {1030, "press touchpad", 1029},
        },
        transit = {706, 966},
        deadly = {},
        pickups = {
            ["Cafeteria"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Company Store"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Custer's Last Stand"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Data Center"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["DeBeers Dormitory"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Ethnobotanist Group"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Galactic Consolidated News Service"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Galactic Heritage Commission office"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Galactic Heritage Foundation executive offices"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Green Freedom"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Interstellar Expeditionary Force office"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Livingston House"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Managing Director's office"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Mine Entrance"] = {via = {"press touchpad (Exterior Airlock to Colony)", "press touchpad (Tamarack and Custer Consolidated Mining and Extraction Corp.)"}},
            ["Opal rock face"] = {via = {"press touchpad (Exterior Airlock to Colony)", "press touchpad (Tamarack and Custer Consolidated Mining and Extraction Corp.)"}},
            ["Solar Federation of Miners Local 6"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Stevedores and Shuttleport Workers Union, local 2858"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Sumatra Colony reception area"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Sumatra Water Authority"] = {via = {"press touchpad (South Dome Exterior Airlock)"}},
            ["Tamarack and Custer Consolidated Mining and Extraction Corp."] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
            ["Workingmen's Club"] = {via = {"press touchpad (Exterior Airlock to Colony)"}},
        },
    },
    ["The Lattice"] = {
        special = {
            {1508, "step onto blue", 2069},
            {1508, "step onto white", 2589},
            {1958, "step onto blue", 2069},
            {1958, "step onto green", 1508},
            {1958, "step onto white", 2078},
            {2069, "step onto white", 1958},
            {2078, "step onto black", 2589},
            {2078, "step onto blue", 1958},
            {2406, "step onto white", 2589},
            {2457, "step onto grey", 2706},
            {2457, "step onto white", 2589},
            {2589, "step onto black", 2406},
            {2589, "step onto white", 2078},
            {2589, "step onto yellow", 2457},
            {2706, "step onto grey", 2457},
        },
        transit = {},
        deadly = {},
        pickups = {
            ["Annex - Production Complex"] = {via = {"step onto black (Lattice reception area)", "step onto yellow (Transfer node)", "step onto grey (Lattice production complex)"}},
            ["Bali Games"] = {via = {"step onto black (Lattice reception area)", "step onto yellow (Transfer node)"}},
            ["Breakfast in Fur"] = {via = {"step onto blue (Lattice reception area)", "step onto green (Transfer node)"}},
            ["Grant Studios"] = {via = {"step onto black (Lattice reception area)", "step onto yellow (Transfer node)"}},
            ["Maya's Art House"] = {via = {"step onto blue (Lattice reception area)", "step onto green (Transfer node)"}},
        },
    },
    ["The Namesake"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
        },
    },
    ["Titan"] = {
        special = {
            {654, "touch screen", 1159},
            {1160, "touch screen", 653},
            {1352, "use chairlift", 1364},
        },
        transit = {},
        deadly = {906, 969, 970},
        pickups = {
        },
    },
    ["Venus"] = {
        special = {
        },
        transit = {},
        deadly = {},
        pickups = {
            ["Hobbs End admin office"] = {gate = "it's only reached on the Hobbs End mine shuttle, which the tools can't ride yet"},
        },
    },
}
